New headless setup integration
astrogoat/elevar pull request #4
Opened 2023-06-12 19:56 UTC by BaffourAdu

This PR is in relation to => https://linear.app/3zbrands/issue/BYTE-135/elevar-new-headless-setup

2023-06-12 20:30 UTC, mcespo approved these changes
Wow this seems pretty cool

2023-06-12 20:30 UTC, OniiCoder approved these changes
Looks good to me.

2023-06-12 20:46 UTC, bmmage approved these changes

2023-06-12 20:49 UTC, iamkarsoft approved these changes

2023-06-13 12:09 UTC, tonning requested changes

2023-06-13 12:09 UTC, tonning commented on resources/views/script.blade.php
> +  	        "myshopify_domain": "{{ Str::of(settings(Astrogoat\Shopify\Settings\ShopifySettings::class)->url)->replace('https://', '') }}"
Can we make the Shopify app a dependency of this package in the `composer.json` file if we now need it here?

2023-06-14 13:22 UTC, tonning approved these changes

2023-06-14 13:22 UTC, merged